### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/xAzurePack#10]
The Example file contains some out of date and community dependent modules which need to be updated (cManageCertificates). A key part of the example depends on this module so that part will need to be re-worked. In addition, there are some old functions that have been brought into the PowerShell gallery and thus the names need to be updated, such as cAzurePackSetup which is now xAzurePackSetup. In the future I think we're going to enforce that all dependencies within the PS gallery modules only depend on other modules in the gallery.

**Comment by DdenBraver** [comment]
I will take a look at this issue soon, and will replace the community certificate in the example with the now available xCertificate (xPfxImport)

**Comment by DdenBraver** [comment]
@mbreakey3 This issue should be resolved in PR #11

**Comment by mbreakey3** [comment]
Great, thanks! Looks good.
