### ISSUE TITLE
Resource list in readme.md is incorrect

### ISSUE THREAD

**Issue by bgelens** [PowerShell/xAzurePack#2]
The readme.md list xAzureQuickVM as on of the resources but this resource is not present in this module.

![xazurepack](https://cloud.githubusercontent.com/assets/10071039/8761312/366216ba-2d4b-11e5-91a0-c1f5f7ec6bad.png)

**Comment by DdenBraver** [comment]
@bgelens @TravisEz13 This issue has been resolved in Pull request #5
